### ISSUE TITLE
How do I use lodash debounce?

### ISSUE THREAD

**Issue by loopArray** [vuejs/vue-class-component#117]
My code is as follows:
```
    handleWindowResize   = debounce(() => {
        console.log(this.screenWidth);
        this.screenWidth = window.innerWidth;
    }, 100)

    @Watch('screenWidth')
    onScreenWidthChange(newVal: number): void {
        console.log(newVal);
    }
```
But there is no work.
When I change my code like this,
```
    handleWindowResize(): void {
        console.log(this.screenWidth);
        this.screenWidth = window.innerWidth;
    }

    @Watch('screenWidth')
    onScreenWidthChange(newVal: number): void {
        console.log(newVal);
    }
```
It can change values from `screenWidth`. How do I organize this code with debounce?

**Comment by ktsn** [comment]
Please use our [forum](https://forum.vuejs.com) or [chat room](https://vue-land.js.org/) to ask your questions. Issue list is reserved for bug reports or feature requests. Thanks.

**Comment by 304NotModified** [comment]
@ktsn 

The forum is down? Or is the link incorrect?

![image](https://user-images.githubusercontent.com/5808377/27807640-93687684-6042-11e7-9c17-454337d752d7.png)

**Comment by ktsn** [comment]
Oops, sorry. The link is incorrect. 
https://forum.vuejs.org is the correct one.

**Comment by Robula** [comment]
Since this issue is already here, why not leave an answer @ktsn ?

**Comment by NikitaKA** [comment]
https://github.com/vuejs/vue-class-component/issues/263#issuecomment-410422120

**Comment by gbalduzzi** [comment]
I found a solution [here](http://www.buaban.com/general/how-to-debounce-function-in-vue-class-component/)

First, you should define your not-debounced function:
```
handleWindowResize(): void {
     console.log(this.screenWidth);
     this.screenWidth = window.innerWidth;
}
```

Then, use debounce with this function instead of an anonymous one:

`handleWindowResizeDebounced = debounce(this.hanfleWindowResize, 100)`

Now you simply need to call `handleWindowResizeDebounced` and you will have your debounced function without the need of an additional dependency
