### ISSUE TITLE
Does createDecorator can't decorate classes?

### ISSUE THREAD

**Issue by vwxyutarooo** [vuejs/vue-class-component#155]
I'm not sure is it bug or correct behave, Following code was working until v5.0.1.

```js
const Test = createDecorator((options) => {
  const mergedOptions = Object.assign({}, {
    name: 'component-sample',
    props: Object.assign({}, {
      a: {
        type: String,
        default: ''
      }
    }, options.props)
  }, options);

  options = mergedOpitons;
});


@Component({
  props: {
    b: {
      type: String,
      default: ''
    }
  }
})
@Test
export default class ComponentSample extends Vue {}
```

Wen I update to 5.0.2, then `createDecorator` not called which shows in above.
Wwhat's happend between 5.0.1 and 5.0.2? And any suggestion to alternative.
Thanks.

**Comment by ktsn** [comment]
Hmm, `createDecorator` was actually not intended to use for class decorator. 😞 

The problem is that the internal object that stores applied custom decorators is changed in v5.0.2. It was a singleton object until v5.0.1 but it will be created for each class component since v5.0.2 to solve #104.

I guess we can simply solve this. I'll investigate it later.

**Comment by oyaschuk** [comment]
As an alternative you can apply your decorator to render function (or any other).
