### ISSUE TITLE
Typescript error

### ISSUE THREAD

**Issue by fsx950223** [vuejs/vue-class-component#164]
![image](https://user-images.githubusercontent.com/17592563/31535611-42036e3e-b02e-11e7-8cda-7fba400735d3.png)
version:
Vue:2.5
Vue-class-component:6.0.0

**Comment by fsx950223** [comment]
I'm sorry.It's a problem about vue-property-decorator

**Comment by kaorun343** [comment]
I've done updating `vue-property-decorator`, so check its new version, please.

**Comment by motin** [comment]
Getting the same error (`error TS2702: 'Vue' only refers to a type, but is being used as a namespace here.`), and since the stack trace reports this error to stem from vue-class-component, maybe it is still relevant to have the issue open here until a fix has been documented?

@kaorun343 Indeed the problem goes away if the version constraint for vue-property-decorator is set to ^6.0.0
