### ISSUE TITLE
Life cycle functions never called in IE9 and 10 when using typescript

### ISSUE THREAD

**Issue by pcmulder** [vuejs/vue-class-component#192]
In IE9 and IE10, the life cycle functions are never called if I use the decorator. If I export an object, it works just fine.

Class (not working): https://github.com/pcmulder/ts-vue-class-component
Object (working): https://github.com/pcmulder/ts-vue-class-component/tree/object

Is there anything I'm missing or not getting?

**Comment by ktsn** [comment]
Thanks for reporting this.

This is because IE9 and 10 does not have `__proto__`, then the component constructor has Vue's static properties as its own property in TypeScript. This causes unintended overwrite of components `options` object that includes lifecycle hooks.

**Comment by ktsn** [comment]
Meanwhile you can use v6.0.0. this should not happen on that version.

**Comment by silkentrance** [comment]
I am experiencing the same here with chrome.

Simply put, the reason for this is 

https://github.com/vuejs/vue-class-component/blob/fd737365bad081e99cb7204317cd37ce7c69f572/src/component.ts#L40

while vue-router will extract these guards directly from the def.options object


https://github.com/vuejs/vue-router/blob/d539788df8394efe41c1534e1e9d1555aa2edbe2/src/history/base.js#L262


What would be the best solution now. Register the guards on def.options or on def.options.methods? Is there even a global beforeRoute*? When not, registering these hooks on def.options should make more sense instead of registering them with def.options.methods, as the latter is actually not supported by vue-router.

**Comment by silkentrance** [comment]
As a side node, when using babel everything works just fine. Wondering why, though.

**Comment by ktsn** [comment]
I saw your reproduction in vue-router issue. The reason is you are registering the hooks after declaring component. As stated in readme you have to register it before component declaration.

**Comment by silkentrance** [comment]
@ktsn hmpf, may I be so stupid? next try...

**Comment by silkentrance** [comment]
@ktsn while your are correct in that the order by which the components are loaded and the respective hooks are registered, and even when reorganising the sources, it still fails.

**Comment by silkentrance** [comment]
```
```

**Comment by ktsn** [comment]
Then could you open a new issue with the code? It probably be different issue with this issue.

**Comment by silkentrance** [comment]
@ktsn will do
