### ISSUE TITLE
[Feature Request]Adding options to disabe auto inject data,method or computed

### ISSUE THREAD

**Issue by lessu** [vuejs/vue-class-component#243]
Thanks for providing vue coder a great tool for writing MVVM in OOP style. vue-class-component is such a great work that make larger SPA project possible.

But recently,We are working on a project with a little bit more complexity.
As more logic, more control flow and more design pattern added.Auto injecting making source code hard to mantain.

1.We have many private member which does not have to an $data. Without obvious distinctions.$data which represent the data on UI is massively tangled with logic data, making source code look bad.

2.`method`, private methods , UI methods, and methods for public interface should be sepreated.

3.`get` is auto convert to computed with a very strong cache, this is convenient. However, we are heavy users of `get` while coding , computed property make every calculation without $data permanent cached, so we have to give up using `get` in many case. 

'd like to show you what I am dreaming
```ts
@AutoDataOff
@AutoMethodOff
@AutoComputedOff
@Component
export default class SomeVue extends Vue{
    @Data
    title : string;

    // don't add to $data
    type: 0|1;
    
    // private mthod
    calcSomething(){
        ....
    }
    
    @Method
    buttonClicked(){
         ...
    }

    // will not convert to a computed,and we can using getter again
    get keyId(){
         ...
    }

    @Computed('titleStyle')
    function titleStyle(){
          return ....
    }
}
```

We will be appreciated with that if adding switch to those auto inject mechanism.

==========================================================================

Actually we have already cloned this git and made some effort to make it possible,It is untested and maybe lots of bugs though.
As long as decided to add this feature , we are happy to make a pull request.

**Comment by ktsn** [comment]
Thanks for suggestion. However, we won't add features that Vue core doesn't have in vue-class-component since its purpose is to transform Vue component definition with class style form.

In addition, some problems you are raising is actually solvable without API addition. (They are known solutions in pure Vue syntax actually)

1. If you don't want to make properties reactive, you can declare them in created hook.

  ```js
  @Component
  export default class SomeVue extends Vue {
    created () {
      this.notReactive = 'foo'
    }
  }
  ```

2. IMO, this is design problem of your app. vue-class-component cannot do anything for you about that.

3. If you don't want to cache computed properties, you should use methods instead. It's stated in [Vue docs](https://vuejs.org/v2/guide/computed.html#Computed-Caching-vs-Methods)
