### ISSUE TITLE
hot reload?

### ISSUE THREAD

**Issue by michaelkrupp** [vuejs/vue-class-component#28]
Are there any plans to support hot-reloading of templates like for example [vueify] does?

[vueify]: https://github.com/vuejs/vueify/blob/master/lib/compiler.js#L157

**Comment by ktsn** [comment]
In my understand, unfortunately, vue-class-component cannot include hot reloading feature because it cannot have code generator as it is runtime library.

To provide hot reloading, we need to trigger [vue-hot-reload-api](https://github.com/vuejs/vue-hot-reload-api) on hot reload and its code have to be placed on **updated file**. vue-loader and (not sure but probably) vueify inject the code while transform `.vue` files.

FYI: The hot reload feature of vue-loader and vueify should also work with using `vue-class-component`.

**Comment by tonypee** [comment]
I just realized that using vue-class-component is the cause of my hmr not working.. quite disappointing. Are there plans to get around this?

**Comment by ktsn** [comment]
vuejs/vue#4976 ?

**Comment by s-KaiNet** [comment]
> FYI: The hot reload feature of vue-loader and vueify should also work with using vue-class-component.   

I found that to make it work with TypeScript you should provide additional configuration, because `ts-loader` doesn't support hmr with default settings.    
1. Set `transpileOnly: true` for `ts-loader`. In that case we lose type checking.
2. TypeScript without type checking is useless. For type checking install [fork-ts-checker-webpack-plugin](https://github.com/Realytics/fork-ts-checker-webpack-plugin) with below config:  
```js
new ForkTsCheckerWebpackPlugin({
      tslint: true,
      vue: true
    }),
```  
I've created starter project to demonstrate this approach - [vue-ts-sfc-webpack-hmr](https://github.com/s-KaiNet/vue-ts-sfc-webpack-hmr)   
Starter doesn't use vue-class-component, however everything should be valid for vue-class-component with TypeScript as well.
