### ISSUE TITLE
Props declaration example in README

### ISSUE THREAD

**Issue by Jinjiang** [vuejs/vue-class-component#286]
I found the code example in README about props declaration like `@Component({ props })` doesn't work any more.

And in the example code:
https://github.com/vuejs/vue-class-component/blob/master/example/src/App.vue#L29:L35

It uses `X = Vue.extend({ props })` first, and then `class Y extends X`. Is that README outdated or does it have some other reasons?

Thanks.

**Comment by ktsn** [comment]
The example in TypeScript is written such because props type inference works so that the users don't have to write redundant type info as class properties.
Writing component option in `@Component` decorator is totally valid as well.

If it does not work, it would be a bug. Could you provide a reproduction for that?

**Comment by Jinjiang** [comment]
I have reproduced that but it's not a bug, but just a config error in VS Code (Seems VS Code would only read the `tsconfig` in the root of a project. So it missed `example/tsconfig` and shows error messages).
Sorry for my stupid mistake. 😅
