### ISSUE TITLE
use Mixins extends ,Parent Component Mixing of Child Components

### ISSUE THREAD

**Issue by meihuanyu** [vuejs/vue-class-component#321]
example
```
  class father {
        render(){
            retrun <div>
                    {this.sonRender()}
              </div>
        } 
    }
 class son{
        sonRender(){
             return <son />
         }
    }
```

**Comment by ktsn** [comment]
Please describe at least:

- whether your issue is feature request or bug report.
- If it is bug report, provide:
  - Vue and vue-class-component version
  - expected behavior
  - actual behavior
  - self-contained reproduction
- If it is feature request, describe:
  - API that you want to propose
  - motivation to introduce the new API
