### ISSUE TITLE
Rename getters and setters of computed properties to the name of the computed property

### ISSUE THREAD

**Issue by maritaria** [vuejs/vue-class-component#332]
When writing a class with computed properties, the error stack trace reports the function name as 'get'. This is because the function is defined [here](https://github.com/vuejs/vue-class-component/blob/master/src/component.ts#L57).
It would be useful to set the name of the function to the name of the property or some form of `get_${computedPropertyName}` so it is more readable and you dont have to rely on the line number to figure out what getter/setter the error occurred in.

This [stackoverflow post](https://stackoverflow.com/a/33067824) details about ways to change the name of a function.

```html
<template>
    <p>{{sayMyName}}</p>
</template>
```
```javascript
@Component
class MyComponent extends Vue {
  get sayMyName() {
    throw new Error('oopsie');
    // I want the console to report 'sayMyName' somewhere in the stack as the function name, preferrably with indication that it is the getter
  }
}
```
Rough untested solution:
```javascript
// https://github.com/vuejs/vue-class-component/blob/master/src/component.ts#L54
const computedProperty = {
  get: descriptor.get,
  set: descriptor.set
};
// This may possibly affect the name of descriptor.get since the function, for less changes to code this could also be done by changing descriptor.get and descriptor.set before assigning using the existing code.
Object.defineProperty(computedProperty.get, 'name', `getter__${key}`);
Object.defineProperty(computedProperty.set, 'name', `setter__${key}`);
(options.computed || (options.computed = {}))[key] = computedProperty;
```

**Comment by ktsn** [comment]
Thank you for suggesting this. But I don't think modifying function name is a good idea.

The current getter/setter function name actually does not come from `vue-class-component`. It just uses original method name which means the native getter/setter name is set as `get` and `set`. In fact, if you throw some errors in native getter/setter in a class, it prints `get` or `set` too.

Because `vue-class-component` is created for writing Vue component by class style syntax, I would not want to make difference between class component and native class.
