### ISSUE TITLE
Vue 3 Support?

### ISSUE THREAD

**Issue by theironcook** [vuejs/vue-class-component#354]
Sorry that this isn't a bug report or confusion on how to you your libraries :)

I have a large code base in development that leverages vue-class-component and vue-property-decorator.  Thank you for sharing your libraries - they help remove a lot of clutter in our code base :)

@ktsn and @kaorun343 - are you planning to update your libraries to be compatible with Vue 3 and the new "Functions API"?  It appears like you probably won't need to do much because the existing vue component options will still be supported...  But are you following along with Vue 3 and planning to make sure your libraries will be compatible?

**Comment by ktsn** [comment]
This is frequently asked question. We will support Vue 3 as well.
As for function-based component API, we don't directly support it because it's impossible to infer its type in class syntax. We can provide some adapter to use functions in class-style component but we should think about it after the API spec is discussed well.

**Comment by service-paradis** [comment]
Great to know!
This issue should be pinned in the issues list, so future user who asked themselves this question will see it first!
