### ISSUE TITLE
Test fails for globally registered components

### ISSUE THREAD

**Issue by MrWook** [vuejs/vue-class-component#397]
Hey i found a bug that is related to unit tests. I don't really know if this is the right place but to post a vue related bug into the ts-jest repo seems kinda strange.

Situation:
I have a component `A` that is using a globally registered component `B`.
Component `A` is loaded async into the app.

Problem:
If component `A` is written in typescript with `vue-class-component` and is loaded async, a jest test can't find the globally registered component `B`. 
If component `A` is written without typescript it will work perfectly fine.

Here is a reproduction setup with vue-cli:
https://github.com/MrWook/ts-jest-bug

**Comment by ktsn** [comment]
Because you don't register your component globally... i.e. you don't run `main.ts` in test.

**Comment by MrWook** [comment]
Thats not correct i'm registering it inside the respective test globally.
For `@testing-library/vue` this is happening inside the callback and for the normal test-utils test it is stubbed.

And like i said everything is working fine when it is not written in typescript.

**Comment by ktsn** [comment]
Well, `stubs` of vue-test-utils is not a global registration.
In any cases, this is not a vue-class-component issue as this can be reproduced without it. I confirmed testing failure after rewriting vue-class-component with pure `Vue.extend`.

I'm not sure about the implementation of vue-testing-library but this is likely vue-testing-library issue as I saw similar one in vue-test-utils which the cause was referring different `Vue` constructors between the root and the target component. You may want to file an issue to vue-testing-library.
https://github.com/vuejs/vue-test-utils/issues/790

**Comment by MrWook** [comment]
Thanks a lot. I didn't think about the Vue.extend. 
I extended my reproduction repo with a `vue.extend` example and will open this issue inside the `@vue/test-utils` repo.

**Comment by MrWook** [comment]
For documentation reason here is the link for my new issue. Seems like that vue-test-utils is the correct repository to adress this issue
https://github.com/vuejs/vue-test-utils/issues/1448
