### ISSUE TITLE
error TS2339: Property 'propMessage' does not exist on type 'App'.

### ISSUE THREAD

**Issue by onecentlin** [vuejs/vue-class-component#44]
Execute README example code, and get this error message.

It seems cannot understand variables defined in Component `props` section.

```
error TS2339: Property 'propMessage' does not exist on type 'App'.
```

Develop Environment:

- Typescript: 2.1.4
- Vue: 2.1.6
- vue-class-component 4.3.1

**Comment by HerringtonDarkholme** [comment]
Hi, the example in README is for Babel. 
If you need use property please declare it in class body, it's TypeScript's feature.

@ktsn should we change the documentation, for example adding one comment line of declaration in class body, to indicate this? (Though IMHO TS users should already know that.)

**Comment by ktsn** [comment]
Adding `Example (Babel)` over the code block?

**Comment by HerringtonDarkholme** [comment]
```ts
class App extends Vue {
  // initial data
  msg = 123
  // you need manually add props in TypeScript, like below
  // propMessage: string
  // use prop values for initial data
  helloMsg = 'Hello, ' + this.propMessage
}
```

**Comment by ktsn** [comment]
Hmm, I'm unwilling to add the comment because it is the description of TypeScript rather than vue-class-component.
How about referring to [example/example.ts](https://github.com/vuejs/vue-class-component/blob/master/example/example.ts) from readme? It does not equal to the babel example since it uses render function but I'll rewrite it with template option.

**Comment by HerringtonDarkholme** [comment]
Sounds good to me! :+1:
