### ISSUE TITLE
Any issue with not naming classes?

### ISSUE THREAD

**Issue by shadow-light** [vuejs/vue-class-component#555]
For a long while I've been exporting my classes without names, e.g.

```
@Component({})
export default class extends Vue {
    ....
}
```

But Vite plugins currently [don't take this into account](https://github.com/underfin/vite-plugin-vue2/issues/119) and it causes build failure as they are expecting classes to have a name.

Just wanted to check if there is any value in giving classes a name and whether I should update them all to do so, or whether the plugins should be corrected to support this. Do the names make debugging easier via console etc? Is there any other value to them?

**Comment by Kolobamanacas** [comment]
> Do the names make debugging easier via console etc?

Not via console but with [DevTools](https://headwayapp.co/vue-js-devtools-changelog). Giving component a name allows you to clearly distinguish it in components tree.

![2021-08-13_21-06-23](https://user-images.githubusercontent.com/20444060/129401263-90152e8f-d083-4ca3-8118-a1245b2c458e.png)

Please also notice, that in order to achieve this you would need not only name a class,  but also pass "name" property with class name string to Component's (or Options's for Vue 3) params list.

**Comment by shadow-light** [comment]
Thanks, yea I noticed that a bit later. I ended up making a [Vite plugin](https://github.com/underfin/vite-plugin-vue2/issues/119#issuecomment-897510108) that automatically sets the class name based on the file name which is working well and shows up in dev tools too.

Thanks for clarifying
