### ISSUE TITLE
Do not use extends

### ISSUE THREAD

**Issue by martinoppitz** [vuejs/vue-class-component#71]
Hello.

In owr projects we use a lot of extends classes hierachies. If you design the class style for vue like `extends Vue`. We can't use our currect oop code. It is better to design the framework compatibily with implements.

Inferno and React have the same problem.

In real projects the focus is on the technical (formal) requirements and should leave the inheritance path free.

**Comment by HerringtonDarkholme** [comment]
The technical limitation is that we initialize instance by Vue class and intercept its initialization call.

Without extending a class I don't think there is any way to implement collection of data option.

**Comment by martinoppitz** [comment]
Angular do not block inheritance. (https://angular.io/docs/ts/latest/tutorial/toh-pt3.html)

```js
import { Component, Input } from '@angular/core';

@Component({
  selector: 'my-hero-detail',
})
export class HeroDetailComponent {
}
```

What we need ...

```js
@Component({
  whatever: ...
})
export class ComponentCladd extends CommonClass implements VueComponent {

  constructor() {}

  data() {}
  render() {}
  ...

}
```

**Comment by kaorun343** [comment]
```ts
@Component
class CommonClass extends Vue {}

@Component
class ComponentClass extends CommonClass {}
```

https://github.com/vuejs/vue-class-component/blob/master/test/test.ts#L140

**Comment by HerringtonDarkholme** [comment]
> Angular do not block inheritance.

Vue and Angular is simply different. Vue uses options to define component while Angular uses plain class. This library is just transforming class syntax to option like. 
If you cannot use plain Vue with your own class file, we cannot magically do that for you either.

> export class ComponentClass extends CommonClass implements VueComponent 

This is impossible because we support using props in constructor. https://github.com/vuejs/vue-class-component/blob/master/test/test.ts#L43-L51 

As I have said. 

> The technical limitation is that we initialize instance by Vue class and intercept its initialization call.

This is impossible without intercept parent class initialization.

**Comment by ktsn** [comment]
Since Vue has built-in instance properties/methods, I think we should not define Vue component without inheritance. Also, vue-class-component utilize a prototype method to collect initial data from user declared properties, we cannot provide alternate api. Sorry.
