### ISSUE TITLE
Component selector depend on import name and not on component name?

### ISSUE THREAD

**Issue by donbabbeo** [vuejs/vue-class-component#84]
I'm trying to integrate consistently both VueJs and Typescript in my production and i'm struggling understanding one thing.
I'm using vue-property-decorator to declare Component and everything is working except custom element selector.
I'm defining my main component like that

`import Home from "./components/home.vue";`
`new Vue({`
`	el: "#app",`
`	template: "<test></test>",`
`	components: { Home }`
`});`

where my Home component is defined as

`@Component({ name: "test" })`
`export default class Home extends Vue { ... }`

but this not works and i get the error of unkown custom element: <test>.
If i replace the template element with <home> or change the import name with Test everything works.
Is that how is supposed to work or there is something fishy here?

**Comment by kaorun343** [comment]
@donbabbeo 

Hi.

You need to do like this below. 

```javascript
import Home from './components/home.vue'

new Vue({
  el: '#app',
  template: '<test></test>',
  components: {
    test: Home
  }
})
```

**Comment by donbabbeo** [comment]
@kaorun343 
Thanks.
If i understand correctly that's the way to define Home as a scoped component of app.
I thought that using the attribute name in the component decorator would define it globally.
I'm wrong?
Anyway why importing the component with the same name used in the template works?

**Comment by kaorun343** [comment]
@donbabbeo 

It's because `Home` was lowercased (`home`) by Vue and registered to the root component. 
Unlike Angular (2 or later), when registered a local component, Vue define its property name as a tag name.

Please read this section below.
http://vuejs.org/v2/guide/components.html#Local-Registration

Also, `name` option is here.
http://vuejs.org/v2/api/#name
As in the document, `name` option is used at devtools and it means nothing when working your projects well.

**Comment by donbabbeo** [comment]
@kaorun343 
Thanks, now i understand why i was confused.
Sorry for the trouble.
